### ISSUE TITLE
Business connector exception while browsing history on Project node

### ISSUE THREAD

**Issue by fraga** [fraga/gitax#6]
while on a project node, server stopped with exception

```
The description for Event ID 180 from source Microsoft Dynamics AX cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event: 

Microsoft Dynamics AX Business Connector Session 3.


RPC exception 3762504530 occurred in session 3 process is Ax32.exe thread is 4296(User: Admin, ClientType: GUI)
```

and more details

```
Dynamics Adapter CallStaticClassMethod failed.

External component has thrown an exception.

System.Runtime.InteropServices.SEHException
   at interpret.callStatic(interpret* , UInt32 , Char* )
   at AxCore.AxRuntime.Call(AxRuntime* , String className, String methodName, Type returnType, Object& result, Object[] paramList)
   at Microsoft.Dynamics.AX.ManagedInterop.RuntimeContext.CallStaticClassMethodWithReturnType(String className, String methodName, Type returnType, Object[] paramList)
   at Microsoft.Dynamics.AX.ManagedInterop.RuntimeContext.CallStaticClassMethod(String className, String methodName)
   at Microsoft.Dynamics.Framework.BusinessConnector.Session.DynamicsAdapter.CallStaticClassMethod(String className, String methodName)
```

**Comment by fraga** [comment]
Was never able to reproduce the problem
